### ISSUE TITLE
the url echo win 10 FAQ

### ISSUE THREAD

**Issue by quentin-zhang** [StevenMaude/win10-urls#4]
I run the python and it echo FAQ url 
`https://www.microsoft.com/en-us/software-download/faq`
It s not the download url .^_^

**Comment by StevenMaude** [comment]
Thanks for reporting.

This is because Microsoft now require a `sessionId` parameter in the query string to return the appropriate content with the correct URLs.

In a browser, this appears as an input element value inside the HTML body. It's not immediately obvious how the page derives this; maybe it's added in via some JavaScript.

**Comment by quentin-zhang** [comment]
Thank you.
